[tox]
envlist = pre-commit,py{311,312,313,314,315}-cov,coverage
labels =
    test = py-cov,coverage
skip_missing_interpreters = True

[testenv:pre-commit]
skip_install = True
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure --color=always

# The leading comma generates the "py" environment.
[testenv:py{,311,312,313,314,315}{,-cov}]
depends = pre-commit
package = editable
setenv =
    TOGA_BACKEND = toga_dummy
dependency_groups = test
commands =
    !cov: python -X warn_default_encoding -m pytest {posargs:-vv --color yes}
    cov: python -X warn_default_encoding -m coverage run -m pytest {posargs:-vv --color yes}

[testenv:coverage]
depends = py{,311,312,313,314,315}-cov
skip_install = True
dependency_groups = test
commands =
    python -m coverage combine
    python -m coverage report
